# Generated by Django 6.0.2 on 2026-03-07 03:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanners', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2026, 3, 7, 3, 49, 56, 909136, tzinfo=datetime.timezone.utc))),
                ('completed_at', models.DateTimeField(default=datetime.datetime(2026, 3, 7, 3, 49, 56, 909174, tzinfo=datetime.timezone.utc))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
