# Generated by Django 6.0.2 on 2026-03-07 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scan',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
