# Generated by Django 6.0.2 on 2026-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scan_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='dismissed_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
