# Generated by Django 6.0.2 on 2026-03-06 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 21, 39, 22, 298490)),
        ),
    ]
