# Generated by Django 6.0.2 on 2026-03-07 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 7, 3, 49, 56, 905725, tzinfo=datetime.timezone.utc)),
        ),
    ]
